CREATE TABLE ARMA(
ARMA_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
ARMA_DANO INT NOT NULL,
ARMA_ELEMENTO VARCHAR(50) NOT NULL,
ARMA_TIPO VARCHAR(50) NOT NULL,
ARMA_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE ARTES_ARCANAS (
AA_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
AA_DESC VARCHAR(50) NOT NULL,
AA_CUSTO INT NOT NULL,
AA_TIPO VARCHAR(50)
);

CREATE TABLE ARTES_FISICAS (
AF_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
AF_DESC VARCHAR(50) NOT NULL,
AF_CUSTO INT NOT NULL,
AF_TIPO VARCHAR(50)
);

CREATE TABLE ARTE_UNICA (
AU_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
AU_DESC VARCHAR(50) NOT NULL,
AU_CUSTO INT NOT NULL,
AU_TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE CLASSE (
CLASSE_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
ARTES_ARCANAS INT,
ARTES_FISICAS INT,
CLASSE_NOME VARCHAR(50) NOT NULL,
FOREIGN KEY(ARTES_ARCANAS) REFERENCES ARTES_ARCANAS(AA_ID),
FOREIGN KEY(ARTES_FISICAS) REFERENCES ARTES_FISICAS(AF_ID)
);

CREATE TABLE RACA (
RACA_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
RACA_DESC VARCHAR(50) NOT NULL,
ARTE_UNICA INT,
FOREIGN KEY (ARTE_UNICA) REFERENCES ARTE_UNICA(AU_ID)
);


CREATE TABLE CONTA (
USUARIO_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
EMAIL VARCHAR(50) NOT NULL,
SENHA varchar(50) NOT NULL
);

CREATE TABLE PERSONAGENS (
PERSO_ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
SEXO CHAR(1) NOT NULL,
RACA INT,
ARMA INT,
CLASSE INT,
USUARIO INT,
FOREIGN KEY (RACA) REFERENCES RACA(RACA_ID),
FOREIGN KEY (ARMA) REFERENCES ARMA(ARMA_ID),
FOREIGN KEY (CLASSE) REFERENCES CLASSE(CLASSE_ID),
FOREIGN KEY (USUARIO) REFERENCES CONTA (USUARIO_ID)
);

INSERT INTO CONTA (EMAIL, SENHA) VALUES 
("josewarrior@gmail.com", "shieldblock"),
("sergiomago@terra.com.br", "fireball"),
("danielpaladino@hotmail.com", "magicwall");

INSERT INTO ARMA (ARMA_DANO, ARMA_ELEMENTO, ARMA_TIPO, ARMA_NOME) VALUES
(120, "TREVAS", "KEYBLADE", "OBLIVION"),
(20, "ARCANO", "CAJADO", "MOONSTAFF"),
(150, "LUZ", "LONG SWORD", "LIGHTBRINGER");

INSERT INTO ARTES_ARCANAS (AA_DESC, AA_CUSTO, AA_TIPO) VALUES
("FIREBALL", 12, "FIRE"),
("ICE SHARD", 3, "ICE"),
("FLASH HEAL", 4, "LIGHT"),
("REINFORCE", 5, "EARTH");


INSERT INTO ARTES_FISICAS (AF_DESC, AF_CUSTO, AF_TIPO) VALUES 
("SHIELD BASH", 6, "BLUNT"),
("MYRIAD SLASHES", 8, "SLASH"),
("CHARGE", 10, "BLUNT");

INSERT INTO ARTE_UNICA (AU_DESC, AU_CUSTO, AU_TIPO) VALUES 
("RUNNING WILD", 4, "WIND"),
("DARKFLIGHT", 15, "DARK"),
("LIGHT JUSTICE", 20, "LIGHT");

INSERT INTO CLASSE (ARTES_ARCANAS, ARTES_FISICAS, CLASSE_NOME) VALUE(
4, 1, "WARRIOR"
);

INSERT INTO RACA (ARTE_UNICA, RACA_DESC) VALUE (
1, "HUMAN"
);

INSERT INTO PERSONAGENS (SEXO, RACA, ARMA, CLASSE, USUARIO) VALUE (
"M", 1, 1, 1, 1
);

